title: Co dělám
content: Nabízím výuku angličtiny a to jak online formou tak osobně, ať už u Vás
  doma nebo ve Vaší firmě. Výuku nastavuju **individuálně**. Pokud chcete,
  můžeme si zvolit učebnici a jet podle ní. Nebo budu připravovat hodiny sama
  podle aktuálních požadavků. Vše je o domluvě :-).
